### ISSUE TITLE
部分歌曲存在加载错误的问题

### ISSUE THREAD

**Issue by shigma** [obstudio/QingyunMusicPlayer-WL#49]
1. 七色光之歌等歌曲报错，可能是 RepeatEnd 错误
2. 死体旅行等歌曲未报错但倚音渲染错误
3. 风居住的街道出现未知错误 Token

**Comment by shigma** [comment]
反复的问题已经确定由于 Volta 这个 Token 解析错误导致，已修复。

**Comment by shigma** [comment]
倚音渲染的问题已经确定为 TmSetting.extend 方法设计上的问题，已修复。

**Comment by shigma** [comment]
未知错误 Token 已被发现是由于结合顺序导致的。现采用下面的解决方案：
1. 当优先级参数为奇数时默认向右结合，否则向左结合。
2. 当解析中遇到未知 Token 时，会报错并自动删除。

**Comment by NN708** [comment]
仍然有 *3rd Eye*、*Kurayami no Kazaana* 两首音乐报错，请您检查。
报错信息：
```
/library/Token/Context.js:146
throw new Error()

Error
at Function.arrange (/library/Token/Context.js:146:17)
at TrackSyntax.tokenize (/library/Token/Context.js:100:27)
at Tokenizer.tokenizeTrack (/library/Token/Tokenizer.js:195:27)
at tracklist.map.track (/library/Token/Tokenizer.js:207:48)
at Array.map (<anonymous>)
at Tokenizer.tokenizeSection (/library/Token/Tokenizer.js:207:30)
at Tokenizer.tokenize (/library/Token/Tokenizer.js:144:31)
at new Thulium (/library/Thulium.js:26:13)
at evalmachine.<anonymous>:1:1
at Script.runInContext (vm.js:74:29)
```

**Comment by shigma** [comment]
已解决，这个问题是由于 Benzene 包内的测试函数的简记法与乐章部分记号冲突导致的。
